name: CI

on:
  pull_request:
    branch:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm install
      - run: npm test

      - name: Check eslint
      - run: npm run lint
